- name: My Setup
  hosts: localhost
  connection: local # no ssh
  gather_facts: false
  become: true
  tasks:

    - name: Copy NetworkManager conf.d files
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - etc/NetworkManager/conf.d/disable-interfaces.conf       # disable onboard wifi (damaged antenna)
        - etc/NetworkManager/conf.d/disable-systemd-resolved.conf # use dnscrypt instead
      notify:
        - Restart NetworkManager

    - name: Pulseaudio | disable autoswitch of output port
      ansible.builtin.replace:
        path: /etc/pulse/default.pa
        regexp: '^(load-module module-switch-on-port-available)$'
        replace: '# \1'

    - name: Disable some default services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - switcheroo-control # dbus, 2 gpu cars
        - iio-sensor-proxy   # dbus, sensors (light,rotation,speed)
        - ModemManager       # 2g/3g/4g modems

    - name: tracker | hold packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - tracker
        - tracker-extract
        - tracker-miner-fs

    - name: tracker | remove executions permissions
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - /usr/libexec/tracker-extract-3
        - /usr/libexec/tracker-miner-fs-3

    - name: Install emacs snap
      community.general.snap:
        name: emacs
        classic: true

    - name: Uninstall Ubuntu package # https://www.dbi-services.com/blog/de-ubuntu-ubuntu/
      ansible.builtin.apt:
        name:
          - ubuntu-report      # report metrics to ubuntu
          - popularity-contest # sends stats to ubuntu
          - whoopsie           # sends crash reports
          - apport             # collects data on crash
        state: absent
        purge: true

    - name: Install general packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - build-essential
          - bear
          - git
          - git-lfs
          - adb
          - python3-pip
          - openjdk-21-jre
          - 7zip
          - p7zip-rar # to unzip password protected files
          - unrar
          - dnscrypt-proxy
          - tor
          - silversearcher-ag
          - sqlite3
          - htop
          - bat
          - jq
          - fzf
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - imagemagick
          - tmux
          - tree
          - docker.io
          - docker-buildx
          - whois
          - newsboat
          - shfmt
          - shellcheck
          - fonts-firacode
          - libsqlite3-dev # for emacs/magit?
          - gnome-tweaks   # for mayus/ctrl swap
          - pavucontrol
          - awesome
          - gromit-mpx     # drawing
          - calibre
          - mupdf
          - mumble-server
          - mumble         # both for https://github.com/pzmarzly/mic_over_mumble
          - xclip
          - sxiv
          - mpv

    - name: Disable mumble-server service
      ansible.builtin.systemd_service:
        name: mumble-server
        state: stopped
        enabled: false

  handlers:
    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
