- name: My Setup
  hosts: localhost
  connection: local # no ssh
  gather_facts: false
  become: true
  tasks:

    - name: Copy NetworkManager conf.d files
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - etc/NetworkManager/conf.d/disable-interfaces.conf
        - etc/NetworkManager/conf.d/disable-systemd-resolved.conf
      notify:
        - Restart NetworkManager

    - name: Disable some default services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - switcheroo-control # dbus, 2 gpu cars
        - iio-sensor-proxy # dbus, sensors (light,rotation,speed)
        - ModemManager # 2g/3g/4g modems

    - name: Install emacs snap
      community.general.snap:
        name: emacs
        classic: true

    - name: Uninstall Ubuntu package # https://www.dbi-services.com/blog/de-ubuntu-ubuntu/
      ansible.builtin.apt:
        name:
          - ubuntu-report # report metrics to ubuntu
          - popularity-contest # sends stats to ubuntu
          - whoopsie # sends crash reports
          - apport # collects data on crash
        state: absent
        purge: true

    - name: Install general packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - build-essential
          - bear
          - git
          - git-lfs
          - dnscrypt-proxy
          - silversearcher-ag
          - htop
          - bat
          - jq
          - zsh
          - adb
          - imagemagick
          - tmux
          - tree
          - docker.io
          - docker-buildx
          - whois
          - newsboat
          - fonts-firacode
          - libsqlite3-dev # for emacs/magit?
          - gnome-tweaks # for mayus/ctrl swap
          - pavucontrol
          - awesome
          - xclip
          - sxiv
          - mpv

  handlers:
    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
