- name: create activity db
  become_user: postgres
  community.postgresql.postgresql_db:
    name: activity
    comment: used by my sleeper program

- name: create logger user
  become_user: postgres
  community.postgresql.postgresql_user:
    db: activity
    name: sleeper
    password: ""
    expires: infinity

# TODO: install sleeper
# TODO: create activity.events table...

- name: grant privs to user logger
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: activity
    privs: SELECT,INSERT,UPDATE
    objs: events
    roles: sleeper
    grant_option: false
