- name: Install general packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - newsboat
      - w3m
      - libxml2-dev         # rdrview
      - libcurl4-gnutls-dev # rdrview
      - libseccomp-dev      # rdrview

# TODO: Build&Install rdrview
# https://github.com/eafer/rdrview

- name: install cli-view
  tags: [cli-view]
  quera.github.install_from_github:
    repo: azimut/cli-view
    asset_regex: cli-view_.*_linux_amd64\.tar\.gz
    move_rules:
      - src_regex: twitterview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: hackerview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: fourchanview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: vichanview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: redditview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: lobstersview
        dst: /home/sendai/bin
        mode: 0755
      - src_regex: discourseview
        dst: /home/sendai/bin
        mode: 0755

- name: install 4chan-rss
  tags: [4chan-rss]
  quera.github.install_from_github:
    repo: azimut/4chan-rss
    asset_regex: 4chan-rss_.*_linux_amd64\.tar\.gz
    move_rules:
      - src_regex: 4chan-rss
        dst: /home/sendai/.config/newsboat/feeds
        mode: 0755

- name: install twitch-rss
  tags: [twitch-rss]
  quera.github.install_from_github:
    repo: azimut/twitch-rss
    asset_regex: twitch-rss_.*_linux_amd64\.tar\.gz
    move_rules:
      - src_regex: twitch-rss
        dst: /home/sendai/.config/newsboat/feeds
        mode: 0755

- name: install github-rss
  tags: [github-rss]
  quera.github.install_from_github:
    repo: azimut/github-rss
    asset_regex: github-rss_.*_linux_amd64\.tar\.gz
    move_rules:
      - src_regex: github-rss
        dst: /home/sendai/.config/newsboat/feeds
        mode: 0755
      - src_regex: gitorg-rss
        dst: /home/sendai/.config/newsboat/feeds
        mode: 0755
      - src_regex: gitissue-rss
        dst: /home/sendai/.config/newsboat/feeds
        mode: 0755
